// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfuU_CldU9ebthY164OIrTcZzB1ZwVE48',
    appId: '1:476872845583:web:dbaf30fdcc0e2f75e6767a',
    messagingSenderId: '476872845583',
    projectId: 'health-watch-4e3db',
    authDomain: 'health-watch-4e3db.firebaseapp.com',
    storageBucket: 'health-watch-4e3db.appspot.com',
    measurementId: 'G-9K1YR45422',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvUBkzW_l0tOMhviGf9rvyqkffEkUQlxQ',
    appId: '1:476872845583:android:965dbf56342b37aee6767a',
    messagingSenderId: '476872845583',
    projectId: 'health-watch-4e3db',
    storageBucket: 'health-watch-4e3db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL7s7ZnNGvUusxhPwTgSuaMuBziDVrTpQ',
    appId: '1:476872845583:ios:876205fe24881806e6767a',
    messagingSenderId: '476872845583',
    projectId: 'health-watch-4e3db',
    storageBucket: 'health-watch-4e3db.appspot.com',
    iosClientId: '476872845583-okgcgeu1phos03r6c3ombdtskjdp91s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL7s7ZnNGvUusxhPwTgSuaMuBziDVrTpQ',
    appId: '1:476872845583:ios:876205fe24881806e6767a',
    messagingSenderId: '476872845583',
    projectId: 'health-watch-4e3db',
    storageBucket: 'health-watch-4e3db.appspot.com',
    iosClientId: '476872845583-okgcgeu1phos03r6c3ombdtskjdp91s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthWatch',
  );
}
